name: 功能新增与优化
description: 提交需要新增或优化的功能
title: "[新增与优化]: "
labels: ["新增与优化"]
body:
  - type: textarea
    attributes:
      label: 描述
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实现效果
    validations:
      required: true
  - type: textarea
    attributes:
      label: 相关的类与方法
    validations:
      required: false
  - type: textarea
    attributes:
      label: 相关内容截图
    validations:
      required: false